site_name: Watchman
nav:
    - 'Strona główna': index.md
    - 'Dokumentacja techniczna':
        - 'Serwisy w frameworku': 135-services-in-framework.md
        - 'Jak działa Workflow': 134-workflow.md
        - 'Do czego używamy klasy Server': 141-do-czego-uzywamy-klasy-server.md
theme: 
    name: 'material'
    features:
        - tabs
    language: pl
    palette:
        primary: 'green'
        accent: 'light green'
markdown_extensions:
    - codehilite
extra_css:
  - stylesheets/codehilite.css
